# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      Image_name: k8s.gcr.io/kube-apiserver
      Image_tag: v1.21.14

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWD }}

      # Get docker hub image name
      # - uses: haya14busa/action-cond@v1
      #   id: docker-hub-image-name-set
      #   with:
      #     cond: ${{ env.Image_platform == 'linux/arm64' }}
      #     if_true: echo "DOCKER_HUB_IMAGE_NAME=feyico/${Image_name//\//-}:${Image_tag:-latest}-arm64" >> "$GITHUB_OUTPUT"
      #     if_false: echo "DOCKER_HUB_IMAGE_NAME=feyico/${Image_name//\//-}:${Image_tag:-latest}" >> "$GITHUB_OUTPUT"

      - name: Get docker hub image name
        id: docker-hub-image-name-set
        run: echo "DOCKER_HUB_IMAGE_NAME=feyico/${Image_name//\//-}" >> "$GITHUB_OUTPUT"
        
      # Runs a set of commands using the runners shell
      - name: Process linux/amd64 images
        env:
          DOCKER_HUB_IMAGE_NAME: ${{ steps.docker-hub-image-name-set.outputs.DOCKER_HUB_IMAGE_NAME }}
        run: |
          docker pull --platform linux/amd64 $Image_name:$Image_tag
          docker tag $Image_name:$Image_tag $DOCKER_HUB_IMAGE_NAME-amd64:$Image_tag
          docker push $DOCKER_HUB_IMAGE_NAME-amd64:$Image_tag

      - name: Process linux/arm64 images
        env:
          DOCKER_HUB_IMAGE_NAME: ${{ steps.docker-hub-image-name-set.outputs.DOCKER_HUB_IMAGE_NAME }}
        run: |
          docker pull --platform linux/arm64 $Image_name:$Image_tag
          docker tag $Image_name:$Image_tag $DOCKER_HUB_IMAGE_NAME-arm64:$Image_tag
          docker push $DOCKER_HUB_IMAGE_NAME-arm64:$Image_tag

      - name: Create manifest list
        env:
          DOCKER_HUB_IMAGE_NAME: ${{ steps.docker-hub-image-name-set.outputs.DOCKER_HUB_IMAGE_NAME }}
        run: |
          docker manifest create $DOCKER_HUB_IMAGE_NAME:$Image_tag \
                                 $DOCKER_HUB_IMAGE_NAME-amd64:$Image_tag \
                                 $DOCKER_HUB_IMAGE_NAME-arm64:$Image_tag --amend
      
      # Runs a set of commands using the runners shell
      - name: Push to Docker Registry
        env:
          DOCKER_HUB_IMAGE_NAME: ${{ steps.docker-hub-image-name-set.outputs.DOCKER_HUB_IMAGE_NAME }}
        run: |
          docker manifest push $DOCKER_HUB_IMAGE_NAME:$Image_tag

